version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Surendra@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  productservice:
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5185:80"

  orderservice:
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - productservice
    ports:
      - "5141:80"

  inventoryservice:
    build:
      context: .
      dockerfile: InventoryService.API/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "5150:80"

volumes:
  sql_data: